# Generated by Django 4.0.4 on 2022-04-12 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcuser', '0002_auto_20220412_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fcuser',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
